STOP_WORDS = ['d', 'saying', 'caption', 'talk', 'talking', 'talked', 'talks', 'talks', 'away', 'image', 'age', 'therefore', 'often', 'told',
'started', 'always', 'air', 'must', 'times', 'use', 'using', 'used', 'uses', 'even', 'thing', 'more', 'less', 'project', 'projects', 'plan', 'plans', 'planning', 'planned',
'sometimes', 'time', 'everyone', 'someone', 'place', 'somebody', 'things', 'anyone', 'recently', 'opens', 'open', 'opened', 'opening', 'multiple',
'everybody', 'anybody', 'inside', 'think', 'thinks', 'thought', 'thinking', 'travel', 'travels', 'traveled', 'travelling',
 'something', 'anything', 'outside', 'indeed', 'play', 'plays', 'eve', 'says', 'top', 'american', 'small', 'big', 'large',
'bottom', 'app', "needn't", 'still', 'ever', 'can', "can't", 'may', 'many', 'visit', 'visits', 'visited', 'visiting', 'trip', 'trips',
'watch', 'watching', 'watched', 'watches', 'contact', 'contacting', 'contacts', 'contacted', 'body', 'bodies', 'make', 'made', 'making', 'makes',
'much', 'plenty', 'least', 'also', "else", 'try', 'drive', 'driving', 'drived', 'drives', 'tries', 'trying', 'tried', "get", 'show', 'next', 'begin', 'end',
'day', 'days', 'month', 'months', 'office', 'offices', 'bay', 'flight', 'flights', 'fly', 'flew', 'flys', 'flying', 'move', 'moved', 'moves', 'moving', 'live', 'lives', 'lived', 'living', 'hand', 'hands', 
'foot', 'feet', 'north', 'south', 'west', 'south', 'weekend', 'weekends', 'weekday', 'weekdays', 'reach', 'reaches', 'reached', 'reaching',
'year', 'years', 'several', 'morning', 'afternoon', 'former', 'evening', 'needn', 'make', 'able', 'know', 'knew', 'knowing', 'knows',
'made', 'both', 'a', 'again', 'weren', 'front', 'back', 'between', 'don', 'to', 'who', 'than', 'ma',
'do', 'such', 'ain', 'were', 'myself', 'or', 'won', 'call', 'calling', 'called', 'calls', 'each', "hadn't", 'more',
'mightn', 'on', 'didn', 'themselves', 'shan', 'shouldn', 'this', 'turn', 'whom', 'site', 'sites', 
"hasn't", 'himself', 'up', 'few', 'by', 'yours', 'theirs', 'was', 'if', 'find', 'finds', 'finding', 'experience', 'experiences',
"aren't", "you'll", "didn't", 'i', "shan't", 'y', 'them', 'where', "could", 'world', 'general',
"couldn't", "shouldn't", 'as', "mightn't", 'are', 'they', 'speak', 'spoke', 'speaks','speaking', 'prepare', 'preparing', 'prepared', 'prepares',
'be', 'its', 'haven', 'files', 'file', 'give', 'given', 'gives', 'gave', 'giving', 'sit', 'sits', 'sitting','sat',
'which', "won't", 'those', 'off', 's', "you've", 'at', 'question', 'questions', 'questioned', 'questioning',
'm', 'doing', 'it', 'report', 'reports', 'reported', 'reporting', 'stay', 'stays', 'staying', 'stayed', 'meet', 'met', 'meeting', 'meetings', 'meets',
'been', 're', 'once', 'go', 'went', "she's", 'having', 'then', 'hers', 'into', 'train', 'car', 'bus',
'for', 'during', 'these', 'before', "ago", 'only', 'with', 'herself', 'your', 'trains', 'cars', 'buses', 'people', 'person', 'persons',
'he', 'how', 'and', 'any', "it's", 'other', 'others', 'very', 'is', 'in', 'own', 'there',
'now', 'through', 'of', 'itself', 'but', 'his', 'most', 'mustn', 'we', 'ours', 'stations', 'station',
"mustn't", 'some', 'am', 'after', 'about', 'have', 'had', 'from', 'so', 'what', 'downtown', 'uptown', 'city', 'rural',
"don't", "that'll", "should've", 'the', 'no', 'aren', "isn't", 'down', 'should',
'ourselves', 'yourselves', 'not', 'has', 'out', 'she', "haven't", "couldn't",
'her', 'that', 'until', 'll', "you'd", 'yourself', 'isn', 'further', 'o', 'him',
'wasn', "would", 'did', "you're", 'because', 'our', 'when', 'why', 'hadn',
'hasn', 'too', 'their', 'an', 'nor', 'does', 'say', 'said', 'my', 've', 'here', 'left', 'right',
'being', 'over', "weren't", 'above', 't', 'below', 'just', 'same', 'you',
'doesn', 'will', 'all', 'against', 'me', "wasn't", 'while', 'wouldn', "doesn't",
'under', 'jan', 'feb', 'mar', 'apr', 'jun', 'jul', 'aug', 'sept', 'nov',
'oct', 'dec', 'january', 'february', 'march', 'april', 'june', 'july',
'august', 'september', 'october', 'november', 'december', 'number', 'one', 'two',
'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'eleven',
'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen', 'seventeen', 'eighteen',
'nineteen', 'twenty', 'first', 'second', 'third', 'fourth', 'fifth', 'sixth',
'seventh', 'eighth', 'ninth', 'tenth', 'Eleventh', 'twelfth', 'thirteenth',
'fourteenth', 'fifteenth', 'sixteenth', 'seventeenth', 'eighteenth',
'nineteenth', 'twentieth', 'monday', 'tuesday','wednesday','thursday','friday',
'saturday','sunday', 'a.m.', 'p.m.', 'thus', 'example', 'particular',
'specifically', 'however', 'nevertheless', 'furthermore', 'moreover', 'besides',
'noon', 'afterward', 'last', 'rarely', 'usually', 'hour', 'hours', 'week',
'weeks', 'minute', 'minutes', 'although', 'rather', 'finally', 'hence', 'since',
 'result', 'resulted', 'especially', 'certainly', 'right', 'left',
'center', '\d\d?:\d{2}(p\.m)?(a\.m)?(am)?(pm)?', '\d*']
