STOP_WORDS = ['d', 'saying', 'caption', 'away', 'image', 'age', 'therefore', 'often', 'told',
'started', 'always', 'must', 'times', 'use', 'even', 'thing', 'more', 'less',
'sometimes', 'time', 'everyone', 'someone', 'somebody', 'things', 'anyone',
'everybody', 'anybody', 'inside', 'something', 'anything', 'outside', 'indeed', 'play', 'plays', 'eve', 'says', 'top',
'bottom', 'app', "needn't", 'still', 'ever', 'can', "can't", 'may', 'many',
'much', 'plenty', 'least', 'also', "else", 'try', 'tries', 'trying', 'tried', "get", 'show', 'next', 'begin', 'end',
'day', 'days', 'month', 'months', 'move', 'moved', 'moves', 'moving', 'live', 'lives', 'lived', 'living', 'hand', 'hands', 
'foot', 'feet', 'north', 'south', 'west', 'south', 'weekend', 'weekends', 'weekday', 'weekdays',
'year', 'years', 'several', 'morning', 'afternoon', 'former', 'evening', 'needn', 'make',
'made', 'both', 'a', 'again', 'weren', 'between', 'don', 'to', 'who', 'than', 'ma',
'do', 'such', 'ain', 'were', 'myself', 'or', 'won', 'call', 'calling', 'called', 'calls', 'each', "hadn't", 'more',
'mightn', 'on', 'didn', 'themselves', 'shan', 'shouldn', 'this', 'turn', 'whom',
"hasn't", 'himself', 'up', 'few', 'by', 'yours', 'theirs', 'was', 'if',
"aren't", "you'll", "didn't", 'i', "shan't", 'y', 'them', 'where', "could",
"couldn't", "shouldn't", 'as', "mightn't", 'are', 'they', 'be', 'its', 'haven',
'which', "won't", 'those', 'off', 's', "you've", 'at', 'm', 'doing', 'it',
'been', 're', 'once', 'go', 'went', "she's", 'having', 'then', 'hers', 'into',
'for', 'during', 'these', 'before', "ago", 'only', 'with', 'herself', 'your',
'he', 'how', 'and', 'any', "it's", 'other', 'very', 'is', 'in', 'own', 'there',
'now', 'through', 'of', 'itself', 'but', 'his', 'most', 'mustn', 'we', 'ours',
"mustn't", 'some', 'am', 'after', 'about', 'have', 'had', 'from', 'so', 'what',
"don't", "that'll", "should've", 'the', 'no', 'aren', "isn't", 'down', 'should',
'ourselves', 'yourselves', 'not', 'has', 'out', 'she', "haven't", "couldn't",
'her', 'that', 'until', 'll', "you'd", 'yourself', 'isn', 'further', 'o', 'him',
'wasn', "would", 'did', "you're", 'because', 'our', 'when', 'why', 'hadn',
'hasn', 'too', 'their', 'an', 'nor', 'does', 'say', 'said', 'my', 've', 'here',
'being', 'over', "weren't", 'above', 't', 'below', 'just', 'same', 'you',
'doesn', 'will', 'all', 'against', 'me', "wasn't", 'while', 'wouldn', "doesn't",
'under', 'jan', 'feb', 'mar', 'apr', 'jun', 'jul', 'aug', 'sept', 'nov',
'oct', 'dec', 'january', 'february', 'march', 'april', 'june', 'july',
'august', 'september', 'october', 'november', 'december', 'number', 'one', 'two',
'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'eleven',
'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen', 'seventeen', 'eighteen',
'nineteen', 'twenty', 'first', 'second', 'third', 'fourth', 'fifth', 'sixth',
'seventh', 'eighth', 'ninth', 'tenth', 'Eleventh', 'twelfth', 'thirteenth',
'fourteenth', 'fifteenth', 'sixteenth', 'seventeenth', 'eighteenth',
'nineteenth', 'twentieth', 'monday', 'tuesday','wednesday','thursday','friday',
'saturday','sunday', 'a.m.', 'p.m.', 'thus', 'example', 'particular',
'specifically', 'however', 'nevertheless', 'furthermore', 'moreover', 'besides',
'noon', 'afterward', 'last', 'rarely', 'usually', 'hour', 'hours', 'week',
'weeks', 'minute', 'minutes', 'although', 'rather', 'finally', 'hence', 'since',
 'result', 'resulted', 'especially', 'certainly', 'right', 'left',
'center', '\d\d?:\d{2}(p\.m)?(a\.m)?(am)?(pm)?', '\d*']
